import { useCallback, useEffect, useState } from "react";
import { Modal } from "../../components/Modal.jsx";
import { IconRefresh } from "../../components/Icons.jsx";
import { api } from "../../lib/api.js";

function useCountdown(expiresAt) {
  const [left, setLeft] = useState(null);

  useEffect(() => {
    if (!expiresAt) return;
    const target = new Date(expiresAt).getTime();
    const tick = () => setLeft(Math.max(0, Math.round((target - Date.now()) / 1000)));
    tick();
    const timer = setInterval(tick, 1000);
    return () => clearInterval(timer);
  }, [expiresAt]);

  return left;
}

/* The QR carries the server address and a signed, expiring session token, so a
   phone that scans it is already bound to this project — it never has to pick
   one. The session is minted on open; "New code" mints another. */
export function ScanModal({ project, onClose }) {
  const [session, setSession] = useState(null);
  const [err, setErr] = useState("");
  const [busy, setBusy] = useState(false);
  const left = useCountdown(session?.expires_at);

  const mint = useCallback(async () => {
    setBusy(true);
    setErr("");
    try {
      setSession(await api.createSession(project.id));
    } catch (e) {
      setErr(`Could not issue a code — ${e.message}`);
    } finally {
      setBusy(false);
    }
  }, [project.id]);

  useEffect(() => { mint(); }, [mint]);

  const expired = left === 0;
  const clock =
    left == null
      ? "—"
      : `${String(Math.floor(left / 60)).padStart(2, "0")}:${String(left % 60).padStart(2, "0")}`;

  return (
    <Modal
      title="Scan with phone"
      subtitle={`${project.code} — ${project.name}`}
      onClose={onClose}
      footer={
        <>
          <div className="spacer" />
          <button className="btn btn-out" onClick={onClose}>Close</button>
          <button className="btn btn-ink" onClick={mint} disabled={busy}>
            <IconRefresh width={16} height={16} />
            New code
          </button>
        </>
      }
    >
      {err ? <div className="banner banner-err">{err}</div> : null}

      <div className="qr-frame">
        {/* SVG generated by our own backend from the session payload. The XML
            prolog it ships with is invalid inside an HTML document, so it goes
            before the markup is inlined. */}
        {session?.qr_svg
          ? <div dangerouslySetInnerHTML={{ __html: session.qr_svg.replace(/^\s*<\?xml[^>]*\?>\s*/, "") }} />
          : <div className="empty">{busy ? "Issuing a code…" : "No code was issued."}</div>}
      </div>

      <ol className="steps">
        <li>Open the scanner app on the site phone.</li>
        <li>Point it at this code — it carries the server, the session and the project.</li>
        <li>Photograph each document; pages upload as you go.</li>
      </ol>

      <div className="kv">
        <div><span>Project</span><span>{project.code}</span></div>
        <div><span>Session</span><span>{session?.session_id?.slice(0, 8) ?? "—"}</span></div>
        <div>
          <span>Expires in</span>
          <span className={`countdown ${expired ? "expired" : left != null && left < 120 ? "warn" : ""}`}>
            {expired ? "expired — tap New code" : clock}
          </span>
        </div>
      </div>
    </Modal>
  );
}
